" VIM Configuration File
" Description: Optimized for C/C++ development, but useful also for other things.
" Author: Gerhard Gappmeier
"

" Vim package manager: Pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" set UTF-8 encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8
" disable vi compatibility (emulation of old bugs)
set nocompatible
" use indentation of previous line
set autoindent
" use intelligent indentation for C
set smartindent
" configure tabwidth and insert spaces instead of tabs
set tabstop=4        " tab width is 4 spaces
set shiftwidth=4     " indent also with 4 spaces
" /==/ set expandtab        " expand tabs to spaces
" wrap lines at 120 chars. 80 is somewaht antiquated with nowadays displays.
set textwidth=120
" turn syntax highlighting on
set t_Co=256
syntax on
" support for python file
autocmd FileType python setlocal et sta sw=4 sts=4
" /==/ colorscheme wombat256
" turn line numbers on
" /==/ set number
" highlight matching braces
set showmatch
" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */
" keep 50 lines of command line history
set history=1000
" match pattern instantly, and highlight all matches
set incsearch
set hlsearch
nmap <silent> <leader>n :silent :nohlsearch<CR>
" turn filetype plugin on
filetype on
filetype plugin on
filetype indent on
" turn on hidden
set hidden
" map <leader> to ,
let mapleader=','
" Enable extended % matching
runtime macros/matchit.vim
" use case-smart searching
set ignorecase
set smartcase
" set the terminal title
set title
" Maintain more context around the cursor
set scrolloff=15
" Enable limited line numbering
set ruler
" Catch trailing whitespace
set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>
" Remap ` to '
" /==/ nnoremap ' `
" /==/ nnoremap ` '

" map Ctrl+a to select all
nmap <C-a> gg<S-v><S-G>

" disable automatic comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" set paste mode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode


" Install OmniCppComplete like described on http://vim.wikia.com/wiki/C++_code_completion
" This offers intelligent C++ completion when typing ‘.’ ‘->’ or <C-o>
" Load standard tag files
set tags+=~/.vim/tags/cpp
set tags+=~/.vim/tags/gl
set tags+=~/.vim/tags/sdl
set tags+=~/.vim/tags/qt4

" Install DoxygenToolkit from http://www.vim.org/scripts/script.php?script_id=987
let g:DoxygenToolkit_authorName="Zeying Peng <zpeng@microstrategy.com>" 

" Enhanced keyboard mappings
"
" in normal mode F3 will save the file
nmap <F3> :w<CR>
" in insert mode F3 will exit insert, save, enters insert again
imap <F3> <ESC>:w<CR>i
" switch between header/source with F4
map <F4> :e %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>
" recreate tags file with F5
map <F5> :!ctags -R –c++-kinds=+p –fields=+iaS –extra=+q .<CR>
" create doxygen comment
map <F6> :Dox<CR>
" build using makeprg with <F7>
map <F7> :make<CR>
" build using makeprg with <S-F7>
map <S-F7> :make clean all<CR>
" goto definition with F12
map <F12> <C-]>
" in diff mode we use the spell check keys for merging
if &diff
  " diff settings
  map <M-Down> ]c
  map <M-Up> [c
  map <M-Left> do
  map <M-Right> dp
  map <F9> :new<CR>:read !svn diff<CR>:set syntax=diff buftype=nofile<CR>gg
else
" /==/  " spell settings
" /==/  :setlocal spell spelllang=en
" /==/  " set the spellfile - folders must exist
" /==/  set spellfile=~/.vim/spellfile.add
" /==/  map <M-Down> ]s
" /==/  map <M-Up> [s
endif

" Display a list of matches when using command-line completion
set wildmenu
set wildmode=full
set wildignore=*.o,*.obj,*.pyc,*.pyo,*.swp,.sconsign.dblite

" Store temporary files in a central spot
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" plugin config
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NERD Commenter
nmap <silent>cc ,c<space>

" CloseTag
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

